### PR TITLE
fix bug on saving env variables to job.env file

### PR DESCRIPTION
**Pull request by ankush13r**
Issue: #9 
modified ` env | grep -e '^JOB_' -e '^GPFS_'  > src/job.env` to ` env | grep -e '^JOB_' -e '^GPFS_' | awk -F= 'length($2) > 0' > src/job.env`

Now if some variables are empty will be removed

### CODE REVIEW

**Comment by ankush13r** [comment]
Yes, i also got the same error, this is if you don't add all variables required, but i think it will fix also your issue
this part is not dynamic for saving variables with var.
```    REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_GROUP: ${{ secrets.REMOTE_GROUP }}
      GPFS_SINGULARITY_IMAGE_REGISTRY_PATH: ${{ vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH }}
      GPFS_JUPYTER_WORKING_DIR: ${{ vars.GPFS_JUPYTER_WORKING_DIR }}
      GPFS_MODELS_REGISTRY_PATH: ${{ vars.GPFS_MODELS_REGISTRY_PATH }}
      MLFLOW_TRACKING_SERVER_URL: ${{vars.MLFLOW_TRACKING_SERV
ER_URL}}
      ```
we have to try if we can do something like:
`cat vars >> $GITHUB_ENV`

**Comment by ankush13r** [comment]
updated workflow using a action that moves all vars to env
```
- name: Set repository variables to env
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(vars) }}
```
Now it's fully ready to merge this pull request

**Comment by PaulNdrei** [comment]
1. That action solves the issue of throwing an error when required secrets are empty.
Referring to https://github.com/langtech-bsc/magma/issues/11

2. Also, it's important to know if the GitHub Actions could reuse versioning; for security reasons, it would be better to ensure that `oNaiPs/secrets-to-env-action@v1` cannot be modified and replace v1 with other code.
I think @v1 is pointing to NaiPs/secrets-to-env-action  v1.5.

**Comment by ankush13r** [comment]
It solves the current issue, but not throws the error. But it's a great idea to throw error, I'll try figure it out.

**Comment by ankush13r** [comment]
@PaulNdrei, Now it's ready to merge.
Description: I've create a new node action that saves all variables or secrets to env and also if you specify the list of key must include, it will check them and throw error if any of them not exists.

**Pull request merged**
